# Native tests, ported from axial. Each runs as a separate process so that a
# crash in one does not hide the others.
foreach(test IN ITEMS core transport owner application)
  add_executable(${test}-tests "tests/${test}_tests.cpp")
  target_link_libraries(${test}-tests PRIVATE axial-options)
endforeach()
target_link_libraries(application-tests PRIVATE advapi32)
add_test(NAME core COMMAND core-tests "${CMAKE_SOURCE_DIR}/tests/fixtures/spaceexplorer-motion.txt" "${CMAKE_SOURCE_DIR}/tests/fixtures/upstream-device-buttons.toml")
add_test(NAME transport COMMAND transport-tests)
add_test(NAME owner COMMAND owner-tests $<TARGET_FILE:axial-service>)
add_test(NAME application COMMAND application-tests)
add_executable(web-tests tests/web_tests.cpp)
target_link_libraries(web-tests PRIVATE axial-web advapi32)
add_test(NAME web COMMAND web-tests $<TARGET_FILE:axial-web-setup>)
add_executable(integration-tests tests/integration_tests.cpp src/bridge.cpp)
target_link_libraries(integration-tests PRIVATE axial-options user32)
target_compile_definitions(integration-tests PRIVATE AXIAL_PREVIEW_TEST)
add_test(NAME integration COMMAND integration-tests $<TARGET_FILE:axial-service> $<TARGET_FILE:siappdll> $<TARGET_FILE:TDxNavLib>)
set_tests_properties(core transport owner application web integration PROPERTIES LABELS native TIMEOUT 120)
